version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: medicos-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medicos
    ports:
      - "5432:5432"
    volumes:
      - medicos_medicos_db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: medicos-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/medicos

volumes:
  medicos_medicos_db_data:
